// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ClearPacketsData, ClearPacketsResponses, GetPacketsData, GetPacketsResponses, GetStatusData, GetStatusResponses, OptionsData, OptionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get router status
 *
 * Returns the current status of the router
 */
export const getStatus = <ThrowOnError extends boolean = false>(options?: Options<GetStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetStatusResponses, unknown, ThrowOnError>({
        url: '/api/status',
        ...options
    });
};

/**
 * Clear all captured packets
 */
export const clearPackets = <ThrowOnError extends boolean = false>(options?: Options<ClearPacketsData, ThrowOnError>) => {
    return (options?.client ?? client).delete<ClearPacketsResponses, unknown, ThrowOnError>({
        url: '/api/packets',
        ...options
    });
};

/**
 * Get captured packets
 *
 * Returns list of captured packets for monitoring
 */
export const getPackets = <ThrowOnError extends boolean = false>(options: Options<GetPacketsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPacketsResponses, unknown, ThrowOnError>({
        url: '/api/packets',
        ...options
    });
};

export const options = <ThrowOnError extends boolean = false>(options?: Options<OptionsData, ThrowOnError>) => {
    return (options?.client ?? client).options<OptionsResponses, unknown, ThrowOnError>({
        url: '/*',
        ...options
    });
};
