// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type StatusDto = {
    status: string;
    message: string;
    uptime: number;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: StatusDto;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type OptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/*';
};

export type OptionsResponses = {
    /**
     * success
     */
    200: string;
};

export type OptionsResponse = OptionsResponses[keyof OptionsResponses];
