// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type StatusDto = {
    status: string;
    message: string;
    uptime: number;
};

export type PacketListDto = {
    packets?: Array<PacketInfoDto>;
    total?: number;
};

export type DashboardStatsDto = {
    status: string;
    uptime: number;
    connectedDevices?: number;
    totalPackets?: number;
    packetsToday?: number;
    wifiEnabled?: boolean;
    bleEnabled?: boolean;
    wifiStatus?: string;
    bleStatus?: string;
    cpuUsage?: number;
    memoryUsed?: number;
    memoryTotal?: number;
    storageUsed?: number;
    storageTotal?: number;
    packetsPerSecond?: number;
    uploadSpeed?: number;
    downloadSpeed?: number;
};

export type LoginResponseDto = {
    success: boolean;
    message: string;
    username?: string;
    userId?: number;
};

export type ProtocolInfoDto = {
    name?: string;
    status?: string;
    connectedDevices?: number;
    description?: string;
    enabled?: boolean;
};

export type SystemResourcesDto = {
    /**
     * CPU usage percentage (0-100)
     */
    cpuUsage?: number;
    /**
     * Used memory in bytes
     */
    memoryUsed?: number;
    /**
     * Total memory in bytes
     */
    memoryTotal?: number;
    /**
     * Used storage in bytes
     */
    storageUsed?: number;
    /**
     * Total storage in bytes
     */
    storageTotal?: number;
};

export type NetworkStatsDto = {
    totalPackets?: number;
    packetsPerSecond?: number;
    uploadSpeed?: number;
    downloadSpeed?: number;
    bytesUploaded?: number;
    bytesDownloaded?: number;
};

export type ProtocolListDto = {
    protocols?: Array<ProtocolInfoDto>;
};

export type PacketInfoDto = {
    id?: string;
    timestamp?: number;
    direction?: string;
    sourceAddr?: string;
    destAddr?: string;
    messageType?: string;
    payloadSize?: number;
    transport?: string;
    encrypted?: boolean;
    rawData?: string;
    decodedHeader?: string;
    decodedPayload?: string;
};

export type SettingsDto = {
    /**
     * WiFi transport enabled
     */
    wifiEnabled?: boolean;
    /**
     * BLE transport enabled
     */
    bleEnabled?: boolean;
    /**
     * Zigbee transport enabled
     */
    zigbeeEnabled?: boolean;
    /**
     * Packet monitor enabled
     */
    monitorEnabled?: boolean;
    updatedAt?: number;
};

export type UpdateSettingsRequestDto = {
    wifiEnabled?: boolean;
    bleEnabled?: boolean;
    zigbeeEnabled?: boolean;
    monitorEnabled?: boolean;
};

export type LoginRequestDto = {
    /**
     * Username for authentication
     */
    username: string;
    /**
     * Password for authentication
     */
    password: string;
};

export type UserInfoDto = {
    id?: number;
    username?: string;
    createdAt?: number;
};

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status';
};

export type GetStatusResponses = {
    /**
     * OK
     */
    200: StatusDto;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetDeviceStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/devices';
};

export type GetDeviceStatusResponses = {
    /**
     * OK
     */
    200: DashboardStatsDto;
};

export type GetDeviceStatusResponse = GetDeviceStatusResponses[keyof GetDeviceStatusResponses];

export type GetSystemStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/system';
};

export type GetSystemStatusResponses = {
    /**
     * OK
     */
    200: SystemResourcesDto;
};

export type GetSystemStatusResponse = GetSystemStatusResponses[keyof GetSystemStatusResponses];

export type GetNetworkStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/status/network';
};

export type GetNetworkStatusResponses = {
    /**
     * OK
     */
    200: NetworkStatsDto;
};

export type GetNetworkStatusResponse = GetNetworkStatusResponses[keyof GetNetworkStatusResponses];

export type ClearPacketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/packets';
};

export type ClearPacketsResponses = {
    /**
     * OK
     */
    200: StatusDto;
};

export type ClearPacketsResponse = ClearPacketsResponses[keyof ClearPacketsResponses];

export type GetPacketsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Maximum number of packets to return
         */
        limit: number;
        /**
         * Offset for pagination
         */
        offset: number;
    };
    url: '/api/packets';
};

export type GetPacketsResponses = {
    /**
     * OK
     */
    200: PacketListDto;
};

export type GetPacketsResponse = GetPacketsResponses[keyof GetPacketsResponses];

export type GetProtocolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/protocols';
};

export type GetProtocolsResponses = {
    /**
     * OK
     */
    200: ProtocolListDto;
};

export type GetProtocolsResponse = GetProtocolsResponses[keyof GetProtocolsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsDto;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: UpdateSettingsRequestDto;
    path?: never;
    query?: never;
    url: '/api/settings';
};

export type UpdateSettingsErrors = {
    /**
     * Internal Server Error
     */
    500: StatusDto;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: SettingsDto;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type OptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/*';
};

export type OptionsResponses = {
    /**
     * success
     */
    200: string;
};

export type OptionsResponse = OptionsResponses[keyof OptionsResponses];

export type LoginData = {
    body: LoginRequestDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Unauthorized
     */
    401: LoginResponseDto;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: LoginResponseDto;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: StatusDto;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: StatusDto;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserInfoDto;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];
